
services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: ${USER_SERVICE_CONTAINER_NAME:-user-service}
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DATABASE_HOST: ${POSTGRES_CONTAINER_NAME:-postgres}
      DATABASE_PORT: ${POSTGRES_PORT:-5432}
      DATABASE_NAME: ${POSTGRES_DB:-store}
      DATABASE_USERNAME: ${POSTGRES_USER:-postgres}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      REDIS_HOST: ${REDIS_CONTAINER_NAME:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${USER_SERVICE_PORT:-8081}:${USER_SERVICE_PORT:-8081}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
#      - ${POSTGRES_CONTAINER_NAME:-postgres}
#      - ${REDIS_CONTAINER_NAME:-redis}
    networks:
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
